/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_truenorth_functions_psf_PsfGenerator */

#ifndef _Included_com_truenorth_functions_psf_PsfGenerator
#define _Included_com_truenorth_functions_psf_PsfGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_truenorth_functions_psf_PsfGenerator
 * Method:    GeneratePsf
 * Signature: ([F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_truenorth_functions_psf_PsfGenerator_GeneratePsf___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_truenorth_functions_psf_PsfGenerator
 * Method:    GeneratePsf
 * Signature: ([F[J[FDDDDDDDII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_truenorth_functions_psf_PsfGenerator_GeneratePsf___3F_3J_3FDDDDDDDII
  (JNIEnv *, jobject, jfloatArray, jlongArray, jfloatArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
