/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_truenorth_gpu_wrappers_YacuDecuWrapper */

#ifndef _Included_com_truenorth_gpu_wrappers_YacuDecuWrapper
#define _Included_com_truenorth_gpu_wrappers_YacuDecuWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_truenorth_gpu_wrappers_YacuDecuWrapper
 * Method:    runYacuDecu
 * Signature: (IIII[F[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_truenorth_gpu_wrappers_YacuDecuWrapper_runYacuDecu
  (JNIEnv *, jobject, jint, jint, jint, jint, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
